int _ABVAR_1_izqA = 0 ;
int _ABVAR_2_izqB = 0 ;
int _ABVAR_3_derA = 0 ;
int _ABVAR_4_derB = 0 ;
int _ABVAR_5_vel = 0 ;
int _ABVAR_6_estado = 0 ;
int _ABVAR_7_g = 0 ;
int _ABVAR_8_duracion = 0 ;
int _ABVAR_9_distancia = 0 ;
int _ABVAR_10_ultra = 0 ;
int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  long duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  if ((duration < 2) || (duration > 300)) return false;
  return duration;
}

int _ABVAR_11_a = 0 ;
int _ABVAR_12_b = 0 ;
int _ABVAR_13_c = 0 ;
int _ABVAR_14_d = 0 ;
int _ABVAR_15_e = 0 ;
int _ABVAR_16_f = 0 ;
void __ardublockDigitalWrite(int pinNumber, boolean status)
{
  pinMode(pinNumber, OUTPUT);
  digitalWrite(pinNumber, status);
}

int _ABVAR_17_pecho = 0 ;

void pulseIn();
void estadoA();
void estadoC();
void estadoB();
void estadoE();
void estadoD();

void setup()
{
  digitalWrite( 3 , LOW );

  Serial.begin(9600);
  pinMode( 13 , OUTPUT);
  pinMode( _ABVAR_4_derB , OUTPUT);
  pinMode( _ABVAR_2_izqB , OUTPUT);
  pinMode( _ABVAR_3_derA , OUTPUT);
  pinMode( _ABVAR_1_izqA , OUTPUT);
  _ABVAR_1_izqA = 5 ;

  _ABVAR_2_izqB = 6 ;

  _ABVAR_3_derA = 9 ;

  _ABVAR_4_derB = 10 ;

  _ABVAR_5_vel = 140 ;

  _ABVAR_6_estado = _ABVAR_7_g ;

  _ABVAR_8_duracion = 0 ;

  _ABVAR_9_distancia = 0 ;

  _ABVAR_10_ultra = 	ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 3 , 4 ) ;

}

void loop()
{
  if (( ( Serial.available() ) > ( 0 ) ))
  {
    _ABVAR_6_estado = Serial.parseInt() ;
  }
  if (( ( _ABVAR_6_estado ) == ( _ABVAR_11_a ) ))
  {
    estadoA();
  }
  if (( ( _ABVAR_6_estado ) == ( _ABVAR_12_b ) ))
  {
    estadoB();
  }
  if (( ( _ABVAR_6_estado ) == ( _ABVAR_13_c ) ))
  {
    estadoC();
  }
  if (( ( _ABVAR_6_estado ) == ( _ABVAR_14_d ) ))
  {
    estadoD();
  }
  if (( ( _ABVAR_6_estado ) == ( _ABVAR_15_e ) ))
  {
    estadoE();
  }
  if (( ( _ABVAR_6_estado ) == ( _ABVAR_16_f ) ))
  {
    if (( ( ( _ABVAR_10_ultra ) <= ( 15 ) ) && ( ( _ABVAR_10_ultra ) >= ( 2 ) ) ))
    {
      digitalWrite( 13 , HIGH );
      estadoC();
      delay( 200 );
      estadoE();
      delay( 500 );
      estadoB();
      delay( 1100 );
      digitalWrite( 13 , LOW );
    }
  }
  else
  {
    estadoA();
  }
  if (( ( _ABVAR_6_estado ) == ( _ABVAR_7_g ) ))
  {
    analogWrite(_ABVAR_4_derB , 0);
    analogWrite(_ABVAR_2_izqB , 0);
    analogWrite(_ABVAR_3_derA , 0);
    analogWrite(_ABVAR_1_izqA , 0);
  }
}

void estadoD()
{
  analogWrite(_ABVAR_4_derB , 0);
  analogWrite(_ABVAR_2_izqB , 0);
  analogWrite(_ABVAR_3_derA , _ABVAR_5_vel);
  analogWrite(_ABVAR_1_izqA , 0);
}

void estadoE()
{
  analogWrite(_ABVAR_4_derB , _ABVAR_5_vel);
  analogWrite(_ABVAR_2_izqB , _ABVAR_5_vel);
  analogWrite(_ABVAR_3_derA , 0);
  analogWrite(_ABVAR_1_izqA , 0);
}

void estadoB()
{
  analogWrite(_ABVAR_4_derB , 0);
  analogWrite(_ABVAR_2_izqB , 0);
  analogWrite(_ABVAR_3_derA , 0);
  analogWrite(_ABVAR_1_izqA , _ABVAR_5_vel);
}

void estadoA()
{
  analogWrite(_ABVAR_4_derB , 0);
  analogWrite(_ABVAR_2_izqB , 0);
  analogWrite(_ABVAR_3_derA , _ABVAR_5_vel);
  analogWrite(_ABVAR_1_izqA , _ABVAR_5_vel);
}

void pulseIn()
{
  __ardublockDigitalWrite(_ABVAR_17_pecho, HIGH);
}

void estadoC()
{
  analogWrite(_ABVAR_4_derB , 0);
  analogWrite(_ABVAR_2_izqB , 0);
  analogWrite(_ABVAR_3_derA , 0);
  analogWrite(_ABVAR_1_izqA , 0);
}


